name: corona
description: A lens implementation, strongly typed, with a build step.
version: 0.3.0-nullsafety.0
homepage: http://www.igindo.com
author: Frank <frank@igindo.com>

environment:
  sdk: '>=2.12.0-51.0.dev <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.12
  build: ^1.5.1
  source_gen: ^0.9.2
  build_runner: ^1.10.6
  build_test: ^1.3.0
  corona_core:
    git: git@github.com:frankpepermans/corona_core.git
  pedantic: ^1.10.0-nullsafety.3
